import { App } from '@slack/bolt';
import cron from 'cron';
import { getProjectStatus } from './statusService';

const DIGEST_CHANNEL = '#daily-standup'; // TODO: Make configurable

/**
 * Schedule the Daily Digest to post every morning
 */
export function scheduleDailyDigest(app: App) {
    // Run at 9:00 AM every weekday (Mon-Fri)
    const job = new cron.CronJob(
        '0 9 * * 1-5',
        async () => {
            console.log('🌅 Running Daily Digest...');

            try {
                const status = await getProjectStatus();

                await app.client.chat.postMessage({
                    channel: DIGEST_CHANNEL,
                    text: '☀️ *Good morning team! Here\'s your Daily Digest:*',
                    blocks: [
                        {
                            type: 'section',
                            text: {
                                type: 'mrkdwn',
                                text: `☀️ *Good morning team! Here's your Daily Digest:*\n\n${status}`,
                            },
                        },
                        {
                            type: 'divider',
                        },
                        {
                            type: 'context',
                            elements: [
                                {
                                    type: 'mrkdwn',
                                    text: '_Generated by AI PM Bot • Use `/pm-status` for on-demand updates_',
                                },
                            ],
                        },
                    ],
                });

                console.log('✅ Daily Digest posted successfully');
            } catch (error) {
                console.error('❌ Failed to post Daily Digest:', error);
            }
        },
        null,
        true,
        'America/New_York' // TODO: Make timezone configurable
    );

    console.log('📅 Daily Digest scheduled for 9:00 AM (Mon-Fri)');
}
